* Gang Management Principles

** Game Description

*** Starting and Recruiting

Outside of gangs require much more crime and heartbreak to create, but
can still be a great help. Creating a Gang in other will offer more
than other , but they will not be a way to destroy the alone.

After creating a gang, you will be able to start recruiting, adding
members to your gang as you gain Respect. While in a BitNode, your
gang and gang member stats will not reset if you install
augmentations.

*** Respect

Earned as your gang members complete tasks, Respect affects your
gang's productivity, including your Faction Reputation (needed to buy
augmentations from your Gang Faction), and the number of recruits you
can have. An individual gang member's Respect is lost or reset if they
Ascend, or are killed in a Territory Warfare clash.

***Ascending

When experienced enough, gang members are offered Ascension, a
permanent boost to their stat multipliers at the cost of resetting
their base stats and equipment to 0, and reducing your Gang Reputation
by the same amount as that member had earned since they last Ascended.

*** Equipping and Managing

Buying Equipment for a gang member will give them a stat boost until
they Ascend or are killed, at which point most equipment will reset.

Augmentations you install on gang members (in the Gang Equipment
subpage) do not reset when they Ascend.

Active gang members earn stats, respect and money based on their
current stats, their equipment, and the effects of Ascending.

*** Wanted, Territory and Clashes

Your gang's "Wanted Level" can make tasks much less productive, and is
affected by the tasks assigned to gang members. "Ethical Hacking" or
"Vigilante Justice" tasks can lower Wanted Level.

"Territory Warfare" is a special task that builds Power for your
gang. If "Territory Clashes" are enabled [see the Territory subpage of
your Gang page], members have a chance to win or lose territory by
clashing with other gangs. The % of Territory you control affects most
aspects of your gang productivity.

Note that gang members can die during clashes, even if your gang wins.

** Gang Basics

*** Mechanics

Gangs have two types: hacking or combat. This effects the tasks that
gang members can engage in, the primary stat needed and how important
territory warfare is.

Gangs can recruit, level up, and equip members. Recruiting more
members requires exponentially increasing amounts of respect. You can
level up members with special training tasks for each of 3 stat
groups:

 - Hacking
 - Combat
 - Charisma

Gangs have several key stats:

 - Respect: needed for recruiting members, getting equipment
            discounts, and gaining faction reputation.
 - Wanted Level: Reduces respect and money gain rates.
 - Power: Affects territory warfare win chance and equipment discounts.

*** Tasks

Gang members can be assigned tasks. Each task has a
difficulty. Hacking gang tasks primarily need high hacking skill,
combat gangs primarily need high combat skill.

We can divide member tasks into three categories:

 - training
 - heating
 - cooling

All tasks earn the member a certain amount of xp/s.

**** Heating Tasks

Heating tasks earn some amount of money/s and/or respect/s for the
gang. They also cause the gang's wanted level to increase at some
rate. All of these values are dependent on the members level in the
relevant skills. Increased level increases the amount of money/s and
respect/s and decreases the amount of wanted level gained per second.

**** Cooling Task

Each gang type has one cooling task that produces money and
_decreases_ wanted level. Cooling tasks do not generate respect!


*** Equipment

You can equip gang members with equipment to give them stat level and
xp bonuses. There are four categories of ephemeral equipment. This
equipment is lost every time a gang member is ascended.

You can also buy gang members augmentations which are retained through
ascensions.

*** Ascending Members

Gang members can get permanent bonuses to their skill levels and
experience gain rates by "Ascending". Experience gathered since their
last ascension is turned into a small multiplier.


** Current management script

The current management strategy is centered around earning money and
leveling up gang members.

One task of each type is chosen based on the gang type. The gang is
partitioned based on a default
