name: Build and Test

on:
  pull_request:
  push:
    branches-ignore:
      - main
  workflow_call:
    outputs:
      artifact_name:
        description: Build artifact name
        value: ${{ jobs.build.outputs.artifact_name }}
      artifact_file:
        description: Build artifact file path
        value: ${{ jobs.build.outputs.artifact_file }}

env:
  ARTIFACT_NAME: scripts

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      artifact_name: ${{ env.ARTIFACT_NAME }}
      artifact_file: ${{ env.ARTIFACT_FILE }}

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Use latest as the release version when building from main branch
        shell: bash
        if: github.ref_type == 'branch' && github.ref_name == 'main'
        run: |
          echo "SCRIPT_VERSION=latest" >> $GITHUB_ENV
          echo "version is: ${{ env.SCRIPT_VERSION }}"

      - name: Store the artifact file name in the environment
        shell: bash
        if: github.ref_type == 'branch' && github.ref_name == 'main'
        run: |
          echo "ARTIFACT_FILE=${{ env.ARTIFACT_NAME }}-${{ env.SCRIPT_VERSION }}.zip" >> $GITHUB_ENV

      - uses: actions/checkout@v4

      - name: Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        run: npm install

      - name: Build
        run: npm run build

      - name: Test
        run: npm exec jest

      - name: Package output
        if: github.ref_type == 'branch' && github.ref_name == 'main'
        run: zip ${{ env.ARTIFACT_FILE }} dist/**/*.js dist/*.js

      - name: Upload Bitburner Runnable Scripts
        uses: actions/upload-artifact@v4
        if: github.ref_type == 'branch' && github.ref_name == 'main'
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: |
            ${{ env.ARTIFACT_FILE }}
