name: Build and Test

on:
  pull_request:
  push:
    branches-ignore:
      - main
  workflow_call:
    outputs:
      artifact_name:
        description: Build Artifact Name
        value: ${{ jobs.build.outputs.artifact_name }}
      artifact_file:
        description: Build Artifact File Path
        value: ${{ jobs.build.outputs.artifact_file }}

env:
  ARTIFACT_NAME: scripts

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      artifact_name: ${{ env.ARTIFACT_NAME }}
      artifact_file: ${{ env.ARTIFACT_NAME }}.zip

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v3
      - name: Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: npm install
      - name: Build
        run: npm run build
      - name: Package output
        run: zip dist/${{ env.ARTIFACT_NAME }}.zip dist/*.js
      - name: Upload Bitburner Runnable Scripts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: |
            dist/${{ env.ARTIFACT_NAME }}.zip
