name: Build and Test

on:
  workflow_call:
    outputs:
      compiled-files:
        description: "A list of all output javascript files"
        value: ${{ jobs.build.compiled-files }}
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      compiled-files: ${{ steps.build.outputs.files }}

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v3
      - name: Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: npm install
      - id: build
        name: Build
        run: |
          npm run build
          echo "::set-output files=$(find dist/ -type f -name '*.js' -print0 | tr '\0' ' ')"
