name: Create Release

on:
  push:
    branches:
      - "main"
    tags:
      - "v*"

jobs:
  build:
    name: "Build"
    uses: "./.github/workflows/build.yml"

  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    needs: build

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: ${{ needs.build.outputs.artifact_name }}
          path: dist

      - name: Create bootstrap script
        shell: bash
        run: bin/make-bootstrap.sh

      - name: Package with specific tag
        if: ${{ github.ref_type == 'tag' && startsWith(github.ref_name, 'v') }}
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          title: "Release ${{ github.ref_name }}"
          files: |
            dist/${{ needs.build.outputs.artifact_file }}

      - name: Package main branch with `latest` tag
        if: ${{ github.ref_type == 'branch' && github.ref_name == 'main' }}
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Latest Main Branch Release"
          files: |
            README.md
            dist/${{ needs.build.outputs.artifact_file }}
