name: Create Release

on:
  push:
    branches:
      - "main"
    tags:
      - "v*"

jobs:
  build:
    name: "Build"
    uses: "./.github/workflows/build.yml"

  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    needs: build

    steps:
      - run: echo ${{ needs.build.outputs.artifact_name }}
      - uses: actions/download-artifact@v3
        with:
          name: ${{ needs.build.outputs.artifact_name }}
          path: dist
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Build Release"
          files: |
            dist/${{ needs.build.outputs.artifact_file }}
